/*
 * Motor_Configurations.h
 *
 * Created: 12/8/2023 7:25:55 PM
 *  Author: 2A_TEAM
 */ 


#ifndef MOTOR_CONFIGURATIONS_H_
#define MOTOR_CONFIGURATIONS_H_

#define MOTOR_LEFTPORT		DIO_PORTB
#define MOTOR_LEFTINPUT1	DIO_PIN4
#define	MOTOR_LEFTINPUT2	DIO_PIN5

#define MOTOR_RIGHTPORT		DIO_PORTB
#define MOTOR_RIGHTINPUT1	DIO_PIN6
#define	MOTOR_RIGHTINPUT2	DIO_PIN7

#define MOTOR_ENABLEPORT	DIO_PORTD
#define MOTOR_ENABLEPIN		DIO_PIN7





#endif /* MOTOR_CONFIGURATIONS_H_ */