/*
 * ULTRASONIC_config.h
 *
 * Created: 05-Nov-23 2:53:24 PM
 *  Author: SEIF EL-DIN SOLTAN
 */ 


#ifndef ULTRASONIC_CONFIG_H_
#define ULTRASONIC_CONFIG_H_

#define ULTRASONIC_TRIGGER_PORT     DIO_PORTD
#define ULTRASONIC_TRIGGER_PIN      DIO_PIN6

#define ULTRASONIC_ECHO_PORT        DIO_PORTD
#define ULTRASONIC_ECHO_PIN         DIO_PIN3



#endif /* ULTRASONIC_CONFIG_H_ */